import { Raleway } from "next/font/google"
import "@/app/globals.css";



import { cn } from "@/lib/utils"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontRaleway = Raleway({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-Raleway",
})

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${fontRaleway.variable}`} >
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontRaleway.variable
        )}
      >
        {children}
      </body>
    </html>
  );
}
